apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
    component: postgres-deployment
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        component: postgres-deployment
    spec:
      containers:
        - name: postgres
          image: mdillon/postgis:9.5
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret-vars
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-vars
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: config-vars
                  key: postgres-db
            - name: POSTGRES_HOST_ENV_NAME
              value: POSTGRES_SERVICE_SERVICE_HOST
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 50m
              memory: 1024Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      volumes:
        - name: pg-data
          gcePersistentDisk:
            pdName: postgres-disk-production
            fsType: ext4
